# Generated by Django 5.1.3 on 2024-12-04 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("diary_image", models.ImageField(upload_to="diaries/")),
                ("extracted_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("description", models.TextField()),
                (
                    "user_diary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="image_generator.userdiary",
                    ),
                ),
            ],
        ),
    ]
