# Generated by Django 5.1.3 on 2024-12-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_generator", "0002_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCustomModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("model_id", models.CharField(max_length=100)),
                ("model_status", models.CharField(default="PENDING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
