# Generated by Django 5.1.3 on 2024-12-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_generator", "0004_userprofile_created_at_userprofile_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="seed_image_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
